name: Update versions

on:
  push:
    branches:
      - main
      - development

jobs:
  update_versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: driver_list

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests toml

    - name: Update versions
      run: python update_list.py

    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update versions" || exit 0
        git push origin HEAD:driver_list

    - name: Checkout code from this branch
      uses: actions/checkout@v3

    - name: show versions
      run: python update_driver_list.py